### PR TITLE
fix #23 Sometimes when you release some item it goes to the wrong place

### LINKED ISSUE #23: Sometimes when you release some item it goes to the wrong place.
Suppose you have a vertical, top-down list with, say, 10 items:

• Go grab item 6 and slowly move it up.
• Item 5 will go down and open some space between items 4 and 5.
• Continue moving item 6 up.
• Now item 4 will go down and open some space between items 3 and 4.
• Continue moving item 6 up, but stop when the top of item 6 is a little bit above the bottom of item 3.
• Then release item 6.
• At this point there was some space between items 3 and 4, and that's where item 6 should land.
• However, as soon as you release it, it will land between items 2 and 3.

It seems to me that, for some reason, the calculation on where the item should land is different from the calculation during the drag itself. So, when you release it, it thinks it should go to a different place.

This is kind of a serious bug, because it is very disconcerting that the item should move to a place different than the one you release it. This makes the list just feel "wrong" sometimes, and this problem seems to happen in both directions, only when the edge of the moving item is a little bit over the edge of the next item.

### PR DESCRIPTION
**Pull request by wonpyohong**
change 1. logics about _closestList are removed.

change 2. _adjustItemTranslations(), onDragUpdated()

change 3. findSwapTargetItem(), onDragEnded()

I added comments on _adjustItemTranslations() and findSwapTargetItem()

### CODE REVIEW

File: example/lib/ui/lang_page.dart [hunk 1]
```diff
@@ -87,7 +87,7 @@ class _LanguagePageState extends State<LanguagePage> with SingleTickerProviderSt
   // * An example of a vertically reorderable list.
   Widget _buildVerticalLanguageList() {
     final theme = Theme.of(context);
-    const listPadding = EdgeInsets.symmetric(horizontal: 0);
+    const listPadding = EdgeInsets.only(right: 30);
```
Comment (bnxm) [inline example/lib/ui/lang_page.dart:90]:
```suggestion
const listPadding = EdgeInsets.zero;
```
Is there a reason, you only applied padding to the right of the list?

File: lib/src/implicitly_animated_reorderable_list.dart [hunk 2]
```diff
@@ -312,91 +308,49 @@ class ImplicitlyAnimatedReorderableListState<E>
...
-  void _adjustPreviousItemTranslations() {
+  /// adjust translations for all non-drag items.
+  ///
+  /// all non-drag items can have 2 states.
+  /// 1. not translated (original position)
+  /// 2. translated (to up or down)
+  ///
+  /// if some item's index is less than _dragIndex, position of the item can move to 1 space down or in place.
+  /// if some item's index is bigger than _dragIndex, position of the item can move to 1 space up or in place.
+  ///
```
Comment (bnxm) [inline lib/src/implicitly_animated_reorderable_list.dart:330]:
```suggestion
  /// Adjust translations for all items that are not being dragged.
  ///
  /// All non-drag items can be in one of two states:
  /// 1. Not translated (original position)
  /// 2. Translated (to up or down)
  ///
  /// If some items index is smaller than _dragIndex,
  /// the position of the item can move to 1 space down or stay in place.
  ///
  /// If some items index is bigger than _dragIndex,
  /// the position of the item can move to 1 space up or stay in place.
```
Looks, good!

File: lib/src/implicitly_animated_reorderable_list.dart [hunk 3]
```diff
@@ -491,20 +445,49 @@ class ImplicitlyAnimatedReorderableListState<E>
...
 
-  void onDragEnded() {
-    if (dragKey == null || _closestList.isEmpty) return;
+  ///
+  /// Finding destination of drag item.
+  /// Items can move to up/down so position can be changed while index is not change.
+  /// We need virtual index reflecting moves.
+  /// Empty space of virtual indexes for non-drag item will be destination index of drag item.
+  ///
+
```
Comment (bnxm) [inline lib/src/implicitly_animated_reorderable_list.dart:454]:
```suggestion
  /// Finds the destination of the dragged item.
  ///
  /// Items can move up or down, so the position of an item can change while the
  /// index is not yet changed.
  ///
  /// We need virtual indices reflecting moves. An empty space in the virtual indices for a non-drag
  /// item will be the destination index of the dragged item.
```

File: lib/src/implicitly_animated_reorderable_list.dart [hunk 4]
```diff
@@ -491,20 +445,49 @@ class ImplicitlyAnimatedReorderableListState<E>
...
+  _Item findSwapTargetItem() {
```
Comment (bnxm) [inline lib/src/implicitly_animated_reorderable_list.dart:455]:
```suggestion
  _Item findSwapTargetItem() {
    // Account for the fact, that a move could have been scheduled,
    // without the widget having fully rebuild itself. In that case, the translation
    // would be 0.0 (and thus the index calculation wrong) and controller.isAnimating will be true.
    //
    // This can be the case, when the user released his finger just
    // short moments after a move had been scheduled (using _dispatchMove()).
    for (final item in _itemBoxes.values) {
      if (item == dragItem) continue;

      final translation = getTranslation(item.key);
      final controller = _itemTranslations[item.key];
      if (translation == 0.0 && controller?.isAnimating == true) {
        return item;
      }
    }
```
Sometimes, when you release an item just after another one had been scheduled to move (up or down), the dragged item would still go to the wrong place, because the translation of the item is still 0.0. By inserting that snippet before, this should not happen.

File: lib/src/implicitly_animated_reorderable_list.dart [hunk 5]
```diff
@@ -491,20 +445,49 @@ class ImplicitlyAnimatedReorderableListState<E>
...
+
+    int dragTargetIndex = _dragIndex;
+    for (int i = 0; i < _itemBoxes.length; i++) {
+      if (!currentIndexList.contains(i)) {
+        dragTargetIndex = i;
+        break;
+      }
     }
 
+    return _itemBoxes.values.firstWhere((item) => item.index == dragTargetIndex);
```
Comment (bnxm) [inline lib/src/implicitly_animated_reorderable_list.dart:476]:
```suggestion
    return _itemBoxes.values.firstWhere(
      (item) => item.index == dragTargetIndex,
      orElse: () => dragItem,
    );
```
`firstWhere` throws `StateError` when it couldn't find an item. So just to be sure.

**Review by bnxm — COMMENTED** [review]
Thanks for trying to fix the issues yourself. It looks pretty good, however I just added one minor addition that I think fixes the issue when an item still sometimes goes to the wrong place.

File: example/lib/ui/lang_page.dart (hunk 1 above)
Comment (wonpyohong) [reply example/lib/ui/lang_page.dart:90]: I was tested with iPhone 11 real device and I cannot long press right edge as following.
https://github.com/flutter/flutter/issues/67252
I don't know whether it is general problem or only my problem..

This is just for testing and doesn't matter

Comment (bnxm) [reply example/lib/ui/lang_page.dart:90]: Ok, thanks.

File: lib/src/implicitly_animated_reorderable_list.dart (hunk 5 above)
Comment (wonpyohong) [reply lib/src/implicitly_animated_reorderable_list.dart:478]: thanks!

File: lib/src/implicitly_animated_reorderable_list.dart (hunk 4 above)
Comment (wonpyohong) [reply lib/src/implicitly_animated_reorderable_list.dart:457]: I confirmed problem and resolving, thanks!

**Comment by wonpyohong** [comment]
Thanks for detailed review. 
Actually, it was my first PR :)
I've learned a lot. Thank you!!

**Comment by bnxm** [comment]
> Thanks for detailed review.
Actually, it was my first PR :)
I've learned a lot. Thank you!!

Nice! 

I think I will publish it as a pre-release to pub.dev soon and when there are no further issues, I will publish it as the production version.
